import { Inter } from "next/font/google";
import "./globals.css";
import CustomLik from "./components/customLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <nav>
          <ul className="flex gap-5 border-b p-5 m-5 justify-center text-2xl">
            <li>
              <CustomLik path="/">হোম</CustomLik>
            </li>
            <li>
              <CustomLik path="/about">About</CustomLik>
            </li>
            <li>
              <CustomLik path="/settings">Settings</CustomLik>
            </li>
            <li>
              <CustomLik path="/dynamic">Users</CustomLik>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
